import { StyleSheet, type StyleProp, type ViewStyle } from 'react-native';
import { FONT_FAMILY } from '../../../theme/typography';
import { START_LIVE_COLORS, startLivePanelStyle } from '../startLive/startLiveStyles';

export const ADD_PRODUCT_COLORS = {
  primary: '#685CF0',
  text: '#18181B',
  title: '#27272A',
  muted: '#71717B',
  placeholder: '#BABABA',
  placeholderSelect: 'rgba(0,0,0,0.25)',
  border: '#DDDDDD',
  borderAccent: '#CBCEFF',
  bannerStart: 'rgba(97, 83, 255, 0.1)',
  bannerEnd: 'rgba(250, 202, 77, 0.1)',
};

export const addProductDrawerProps = {
  bottomPanel: true as const,
  panelStyle: [startLivePanelStyle, { paddingTop: 28 }] as StyleProp<ViewStyle>,
};

export const addProductStyles = StyleSheet.create({
  screen: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 32,
    gap: 24,
  },
  tipsBanner: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.borderAccent,
    borderRadius: 8,
    paddingVertical: 24,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: ADD_PRODUCT_COLORS.bannerStart,
  },
  tipsTextCol: {
    flex: 1,
    gap: 4,
  },
  tipsTitle: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 16,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.text,
  },
  tipsBody: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.text,
  },
  tipsArrow: {
    width: 40,
    height: 32,
    borderRadius: 1000,
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.borderAccent,
    backgroundColor: 'rgba(104, 92, 240, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 20,
    lineHeight: 28,
    color: ADD_PRODUCT_COLORS.title,
  },
  photoBox: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderRadius: 12,
    minHeight: 147,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    padding: 16,
  },
  photoBoxLabel: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 12,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.muted,
    textAlign: 'center',
  },
  photoRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  photoThumb: {
    width: 72,
    height: 72,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  photoThumbImage: {
    width: '100%',
    height: '100%',
  },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoAddTile: {
    width: 72,
    height: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.35)',
  },
  photoAddTileLabel: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 9,
    lineHeight: 12,
    color: ADD_PRODUCT_COLORS.muted,
    textAlign: 'center',
    paddingHorizontal: 4,
  },
  photoOptionHint: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    lineHeight: 16,
    color: '#71717B',
  },
  photoSourceBody: {
    gap: 18,
    width: '100%',
  },
  photoSourceIntro: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 14,
    lineHeight: 20,
    color: '#F4F4F5',
  },
  photoSourceList: {
    gap: 12,
    width: '100%',
  },
  photoSourceRow: {
    minHeight: 76,
    width: '100%',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(203, 206, 255, 0.9)',
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  photoSourceRowDisabled: {
    opacity: 0.45,
  },
  photoSourceIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoSourceTextCol: {
    flex: 1,
    gap: 3,
  },
  photoSourceTitle: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 15,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  photoSourceHint: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    lineHeight: 16,
    color: '#D9D9D9',
  },
  photoCountHint: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: 10,
    lineHeight: 16,
    color: ADD_PRODUCT_COLORS.muted,
    marginTop: 4,
  },
  fields: {
    gap: 12,
  },
  field: {
    gap: 8,
  },
  fieldLabel: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: 10,
    lineHeight: 18,
    letterSpacing: 0.5,
    color: ADD_PRODUCT_COLORS.text,
  },
  pillInput: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 56,
    backgroundColor: 'rgba(255,255,255,0.2)',
    fontFamily: FONT_FAMILY.bold,
    fontSize: 12,
    color: ADD_PRODUCT_COLORS.text,
  },
  pillInputMultiline: {
    borderRadius: 12,
    minHeight: 147,
    textAlignVertical: 'top',
  },
  priceInputWrap: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderRadius: 100,
    minHeight: 56,
    backgroundColor: 'rgba(255,255,255,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  pricePrefix: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 12,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.text,
    marginRight: 4,
  },
  priceInput: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 0,
    fontFamily: FONT_FAMILY.bold,
    fontSize: 12,
    color: ADD_PRODUCT_COLORS.text,
  },
  pillSelect: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 16,
    minHeight: 56,
    backgroundColor: 'rgba(255,255,255,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pillSelectText: {
    flex: 1,
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.placeholderSelect,
  },
  pillSelectTextFilled: {
    color: ADD_PRODUCT_COLORS.text,
    fontFamily: FONT_FAMILY.bold,
  },
  actions: {
    gap: 12,
    marginTop: 8,
  },
  primaryBtn: {
    backgroundColor: ADD_PRODUCT_COLORS.primary,
    borderRadius: 1000,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  primaryBtnDisabled: {
    opacity: 0.5,
  },
  primaryBtnText: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  cancelBtn: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 14,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.primary,
  },
  drawerBody: {
    gap: 24,
    width: '100%',
  },
  drawerHint: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 14,
    lineHeight: 20,
    color: START_LIVE_COLORS.textMuted,
  },
  tierList: {
    gap: 24,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(221,221,221,0.87)',
    paddingBottom: 24,
  },
  tierRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tierTextCol: {
    flex: 1,
    gap: 4,
  },
  tierHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tierTitle: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  tierRange: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  tierHint: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    lineHeight: 16,
    color: START_LIVE_COLORS.textMuted,
  },
  tierRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.borderAccent,
    backgroundColor: 'rgba(104, 92, 240, 0.1)',
  },
  tierRadioOn: {
    borderColor: ADD_PRODUCT_COLORS.primary,
    borderWidth: 2,
    backgroundColor: ADD_PRODUCT_COLORS.primary,
  },
  manualWeightLabel: {
    fontFamily: FONT_FAMILY.regular,
    fontSize: 14,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  manualWeightRow: {
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.border,
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  manualWeightInput: {
    flex: 1,
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    color: START_LIVE_COLORS.textMuted,
    padding: 0,
  },
  manualWeightUnit: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 12,
    color: START_LIVE_COLORS.textMuted,
    marginRight: 4,
  },
  manualWeightHelp: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 11,
    lineHeight: 16,
    color: START_LIVE_COLORS.textMuted,
    paddingHorizontal: 16,
  },
  conditionList: {
    gap: 12,
    width: '100%',
  },
  conditionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.borderAccent,
    borderRadius: 1000,
    paddingHorizontal: 16,
    paddingVertical: 8,
    minHeight: 56,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  conditionRowOn: {
    borderColor: ADD_PRODUCT_COLORS.primary,
    backgroundColor: 'rgba(104, 92, 240, 0.15)',
  },
  conditionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  conditionIcon: {
    width: 32,
    height: 32,
    borderRadius: 1000,
    backgroundColor: '#DBDBDF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  conditionLabel: {
    fontFamily: FONT_FAMILY.bold,
    fontSize: 14,
    lineHeight: 20,
    color: ADD_PRODUCT_COLORS.text,
  },
  saleFormatTextCol: {
    flex: 1,
    gap: 2,
  },
  conditionCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ADD_PRODUCT_COLORS.muted,
    backgroundColor: 'rgba(104, 92, 240, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  conditionCheckOn: {
    borderColor: ADD_PRODUCT_COLORS.primary,
    backgroundColor: ADD_PRODUCT_COLORS.primary,
  },
  weightPresetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(221,221,221,0.35)',
  },
  weightPresetLabel: {
    fontFamily: FONT_FAMILY.semibold,
    fontSize: 14,
    color: '#FFFFFF',
  },
});
